### ISSUE TITLE
有没有兴趣一起刷题和完善代码库？

### ISSUE THREAD

**Issue by leopeng1995** [algorithmslover/2017-interview#1]
我看到了你的这个repo，有没有兴趣接下来的时间一起刷LeetCode和hihoCoder这些题库？邀请你一起来完善这个代码库[acplusplus](https://github.com/leopeng1995/acplusplus)。

**Comment by algorithmslover** [comment]
好啊

**Comment by leopeng1995** [comment]
@algorithmslover 我觉得还是要优先把LeetCode、LintCode这两个题库尽量做个大部分，因为这里都是经典的面试题，难度适中，主要是为了锻炼编程能力。hihoCoder也是一个很好的题库，我觉得它更像是一个引导你入门的习题集，因为上面的题目都是为了讲解某种算法或者数据结构而专门设计的，还有详细的思路指导。

另外，咱们可以尽量把题解做成类似这种[repo](https://github.com/soulmachine/leetcode)的形式，一来方便我们自己复习、归纳和整理，第二是也方便其他人也容易参考。这个[repo](https://github.com/soulmachine/leetcode)的一个缺点是没有完整的程序，我一般在做LeetCode上的问题时，都是写成完整的程序，然后写上测试用例（关于测试用例，有道题比较坑，[String to Integer (atoi)](https://leetcode.com/problems/string-to-integer-atoi/)，这道题我考虑了好多种测试用例，依然会遗漏掉某些特殊的输入）。
